### ISSUE TITLE
Create a Solr image

### ISSUE THREAD

**Issue by lmakarov** [blinkreaction/docker-images#7]
Create a standalone Solr image which can be linked to a web container.
We will most likely need several versions matching those used/available on Acquia.

Some starting points to consider:
 - https://github.com/twinbit/docker-drupal-solr
 - https://github.com/geerlingguy/ansible-role-solr

**Comment by lmakarov** [comment]
Should be resolved with #13 and #14.

Solr images available as:
- blinkreaction/drupal-solr:3.x
- blinkreaction/drupal-solr:4.x

Usage example:

```
solr:
  image: IMAGE
  ports:
    - "8983:8983"
  volumes:
    # Map config files from your solr module
    - "<path to your module>/solr-conf/<SOLRVERSION>:/var/lib/solr/conf"
```

@achekulaev please take a look and provide feedback.
